---
title: "practice"
output: html_document
date: "2026-04-02"
---

# source()
```{r}
source("angling_prepartion.R")
```



# practice


```{r}
library(tidyverse)

# データインポート
data_2024 <- read_csv("angling_data_2024.csv")
data_2025 <- read_csv("angling_data_2025.csv")

# データを結合。結合時に、idが年ごとで区別できるようにしている

data_all <- bind_rows(
  data_2024,
  data_2025
) |>
  mutate(
    respondent_id = paste0(year, "_", id)
  )

data_all |>
  group_by(year) |>
  summarise(
    across(
      everything(),
      ~ sum(is.na(.x))
    )
  )

```


```{r}
# 両方にある変数
intersect(
  names(survey_2024),
  names(survey_2025)
)

# 2024年にしかない変数
setdiff(
  names(survey_2024),
  names(survey_2025)
)

# 2025年にしかない変数
setdiff(
  names(survey_2025),
  names(survey_2024)
)
```


```{r}
df2 <- df |> mutate(
  v10_dummy = case_when(
    v10_formulation_procedure == "知っていて、納得している" | 
      v10_formulation_procedure == "知らないが、納得している" ~ "納得",
    v10_formulation_procedure == "知っているが、納得していない" | 
      v10_formulation_procedure == "知らないし、納得していない" ~ "納得してない",
    TRUE ~ NA_character_
  )
)

data.frame(
  "竿3本" = df2$v17_2_max_rods_three |> sum(na.rm = TRUE) |> round(2),
  "魚3尾" = df2$v17_2_max_catch_three|> sum(na.rm = TRUE) |> round(2),
  "場所取り" = df2$v17_2_no_spot_reservation |> sum(na.rm = TRUE) |> round(2),
  "どれも同じ" = df2$v17_2_all_equally_important |> sum(na.rm = TRUE) |> round(2),
  "わからない" = df2$v17_2_dont_know |> sum(na.rm = TRUE) |> round(2)
) |> 
  pivot_longer(
    cols = everything(),
    names_to = "もっとも重要でないと思うルール",
    values_to = "度数"
  ) |> 
  arrange(desc(度数)) |> 
  ggplot(aes(x = もっとも重要でないと思うルール, y = 度数)) +
  geom_col() 
```


```{r}
df$date <- factor(
  df$date,
  levels = c("9月27日_プレ", "10月4日", "10月5日", "10月17日", "10月19日", "10月24日"),
  ordered = TRUE
)


```


```{r}
df |> count(v6_fishing_days_last_season)
```

