---
title: "v10_formulation_procedure"
output: html_document
date: "2026-06-29"
---

# 準備


```{r message=FALSE}
source("angling_prepartion.R")
```


# × v17_2 ルール（もっとも重要でない）

```{r}
df2 <- df |> filter(v10_formulation_procedure == "知っているが、納得していない" | v10_formulation_procedure == "知らないし、納得していない" )

data.frame(
  "竿3本" = df2$v17_2_max_rods_three |> mean(na.rm = TRUE) |> round(2),
  "魚3尾" = df2$v17_2_max_catch_three|> mean(na.rm = TRUE) |> round(2),
  "場所取り" = df2$v17_2_no_spot_reservation |> mean(na.rm = TRUE) |> round(2),
  "どれも同じ" = df2$v17_2_all_equally_important |> mean(na.rm = TRUE) |> round(2),
  "わからない" = df2$v17_2_dont_know |> mean(na.rm = TRUE) |> round(2)
) |> 
  pivot_longer(
    cols = everything(),
    names_to = "もっとも重要でないと思うルール",
    values_to = "該当率"
  ) |> 
  arrange(desc(該当率)) |> 
  ggplot(aes(x = もっとも重要でないと思うルール, y = 該当率)) +
  geom_col() +
  ylim(0, 0.7) +
  labs(
    title = "ルール策定手順に納得していない人のみ"
  )
```

納得していない人限定で見てみると、魚3尾を低評価する人の割合が明らかに大きい。

```{r}
df2 <- df |> filter(v10_formulation_procedure == "知っているが、納得していない" | v10_formulation_procedure == "知らないし、納得していない" )

data.frame(
  "竿3本" = df2$v17_2_max_rods_three |> sum(na.rm = TRUE) |> round(2),
  "魚3尾" = df2$v17_2_max_catch_three|> sum(na.rm = TRUE) |> round(2),
  "場所取り" = df2$v17_2_no_spot_reservation |> sum(na.rm = TRUE) |> round(2),
  "どれも同じ" = df2$v17_2_all_equally_important |> sum(na.rm = TRUE) |> round(2),
  "わからない" = df2$v17_2_dont_know |> sum(na.rm = TRUE) |> round(2)
) |> 
  pivot_longer(
    cols = everything(),
    names_to = "もっとも重要でないと思うルール",
    values_to = "度数"
  ) |> 
  arrange(desc(度数))
```
度数でも見てみた。


```{r}
df2 <- df |> filter(v10_formulation_procedure == "知っていて、納得している" | v10_formulation_procedure == "知らないが、納得している" )

data.frame(
  "竿3本" = df2$v17_2_max_rods_three |> mean(na.rm = TRUE) |> round(2),
  "魚3尾" = df2$v17_2_max_catch_three|> mean(na.rm = TRUE) |> round(2),
  "場所取り" = df2$v17_2_no_spot_reservation |> mean(na.rm = TRUE) |> round(2),
  "どれも同じ" = df2$v17_2_all_equally_important |> mean(na.rm = TRUE) |> round(2),
  "わからない" = df2$v17_2_dont_know |> mean(na.rm = TRUE) |> round(2)
) |> 
  pivot_longer(
    cols = everything(),
    names_to = "もっとも重要でないと思うルール",
    values_to = "該当率"
  ) |> 
  arrange(desc(該当率)) |> 
  ggplot(aes(x = もっとも重要でないと思うルール, y = 該当率)) +
  geom_col() +
  labs(
    title = "ルール策定手順に納得している人のみ"
  )+
  ylim(0, 0.7) 
```

納得している限定だと3尾ルールの低評価割合は明らかに小さくなる。


```{r}
df2 <- df |> filter(v10_formulation_procedure == "知っていて、納得している" | v10_formulation_procedure == "知らないが、納得している" )

data.frame(
  "竿3本" = df2$v17_2_max_rods_three |> sum(na.rm = TRUE) |> round(2),
  "魚3尾" = df2$v17_2_max_catch_three|> sum(na.rm = TRUE) |> round(2),
  "場所取り" = df2$v17_2_no_spot_reservation |> sum(na.rm = TRUE) |> round(2),
  "どれも同じ" = df2$v17_2_all_equally_important |> sum(na.rm = TRUE) |> round(2),
  "わからない" = df2$v17_2_dont_know |> sum(na.rm = TRUE) |> round(2)
) |> 
  pivot_longer(
    cols = everything(),
    names_to = "もっとも重要でないと思うルール",
    values_to = "度数"
  ) |> 
  arrange(desc(度数)) |> 
  ggplot(aes(x = もっとも重要でないと思うルール, y = 度数)) +
  geom_col()
```

度数でもみてみた。




